return {
    weapons = {
        [`weapon_raycarbine`] = true
    },
    peds = {
        [`a_m_m_acult_01`] = true,
        [`a_m_m_tranvest_01`] = true,
        [`a_c_dolphin`] = true,
        [`mp_m_marston_01`] = true,
        [`mp_m_niko_01`] = true,
        [`ig_johnnyklebitz`] = true,
        [`u_m_y_juggernaut_01`] = true,
    },
    vehicles = {
        [`savage`] = true,
        [`valkyrie`] = true,
        [`valkyrie2`] = true,
        [`annihilator2`] = true,
        [`apc`] = true,
        [`barrage`] = true,
        [`halftrack`] = true,
        [`khanjali`] = true,
        [`minitank`] = true,
        [`rhino`] = true,
        [`scarab`] = true,
        [`scarab2`] = true,
        [`scarab3`] = true,
        [`thruster`] = true,
        [`trailersmall2`] = true,
        [`vetir`] = true,
        [`oppressor`] = true,
        [`oppressor2`] = true,
        [`insurgent`] = true,
        [`insurgent2`] = true,
        [`insurgent3`] = true,
        [`menacer`] = true,
        [`hydra`] = true,
        [`jet`] = true,
        [`lazer`] = true,
        [`volatol`] = true,
        [`vigilante`] = true,
        [`tractor`] = true,      
    },
    objects = {}
}